class SerialConnectionDefinition:
    CALIB_BEGIN = 1
    CALIB_END = 2

    EXP_BEGIN = 3
    EXP_END = 4

    WINDOW_CLOSE_BEGIN = 5
    WINDOW_CLOSE_END = 6

    # Mail related events
    MAIL_HOMESCREEN_BEGIN = 7
    MAIL_HOMESCREEN_END = 8
    MAIL_NOTIFICATION_BEGIN = 9
    MAIL_NOTIFICATION_END = 10
    MAIL_CONTENT_BEGIN = 11
    MAIL_CONTENT_END = 12

    # File manager (dragging and opening)
    FILE_MANAGER_HOMESCREEN_BEGIN = 13
    FILE_MANAGER_HOMESCREEN_END = 14
    FILE_MANAGER_DRAGGING_BEGIN = 15
    FILE_MANAGER_DRAGGING_END = 16
    FILE_MANAGER_OPENING_BEGIN = 17
    FILE_MANAGER_OPENING_END = 18

    # Trash bin
    TRASH_BIN_HOMESCREEN_BEGIN = 19
    TRASH_BIN_HOMESCREEN_END = 20
    TRASH_BIN_SELECT_BEGIN = 21
    TRASH_BIN_SELECT_END = 22
    TRASH_BIN_CONFIRM_BEGIN = 23
    TRASH_BIN_CONFIRM_END = 24

    # Notes
    NOTES_HOMESCREEN_BEGIN = 25
    NOTES_HOMESCREEN_END = 26
    NOTES_REPEAT_BEGIN = 27
    NOTES_REPEAT_END = 28

    # Browser
    BROWSER_HOMESCREEN_BEGIN = 29
    BROWSER_HOMESCREEN_END = 30
    BROWSER_NAVIGATION_BEGIN = 31
    BROWSER_NAVIGATION_END = 32
    BROWSER_CONTENT_BEGIN = 33
    BROWSER_CONTENT_END = 34

    # Questions
    QUESTION_BASE = 100
    QUESTION_LEAP = 10
    ## Answered questions will be encoded as
    ## QUESTION_BASE + QUESTION_LEAP * QUESTION_INDEX + QUESTION_RATING

    EEG_STOP_RECORDING = 255
    EEG_START_RECORDING = 254